<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WPML_Admin_Notifier' => $baseDir . '/classes/class-wpml-admin-notifier.php',
    'WPML_Admin_String_Filter' => $baseDir . '/classes/filters/class-wpml-admin-string-filter.php',
    'WPML_Auto_Loader' => $vendorDir . '/wpml/commons/src/wpml-auto-loader.php',
    'WPML_Change_String_Domain_Language_Dialog' => $baseDir . '/classes/string-translation-ui/class-wpml-change-string-domain-language-dialog.php',
    'WPML_Change_String_Language_Dialog' => $baseDir . '/classes/string-translation-ui/class-wpml-change-string-language-dialog.php',
    'WPML_Custom_Post_Slug_UI' => $baseDir . '/classes/slug-translation/class-wpml-custom-post-slug-ui.php',
    'WPML_Dependencies' => $vendorDir . '/wpml/commons/src/dependencies/class-wpml-dependencies.php',
    'WPML_Displayed_String_Filter' => $baseDir . '/classes/filters/class-wpml-displayed-string-filter.php',
    'WPML_Language_Of_Domain' => $baseDir . '/classes/class-wpml-language-of-domain.php',
    'WPML_Rewrite_Rule_Filter' => $baseDir . '/classes/slug-translation/class-wpml-rewrite-rule-filter.php',
    'WPML_ST_Admin_Blog_Option' => $baseDir . '/classes/admin-texts/class-wpml-st-admin-blog-option.php',
    'WPML_ST_Admin_Option_Translation' => $baseDir . '/classes/admin-texts/class-wpml-st-admin-option-translation.php',
    'WPML_ST_Admin_String' => $baseDir . '/classes/class-wpml-st-admin-string.php',
    'WPML_ST_Blog_Name_And_Description_Hooks' => $baseDir . '/classes/filters/class-wpml-st-blog-name-and-description-hooks.php',
    'WPML_ST_ICL_String_Translations' => $baseDir . '/classes/records/class-wpml-st-icl-string-translations.php',
    'WPML_ST_ICL_Strings' => $baseDir . '/classes/records/class-wpml-st-icl-strings.php',
    'WPML_ST_Label_Translation' => $baseDir . '/classes/filters/class-wpml-st-label-translation.php',
    'WPML_ST_Records' => $baseDir . '/classes/records/class-wpml-st-records.php',
    'WPML_ST_String' => $baseDir . '/classes/class-wpml-st-string.php',
    'WPML_ST_String_Factory' => $baseDir . '/classes/class-wpml-st-string-factory.php',
    'WPML_ST_String_Statuses' => $baseDir . '/classes/class-wpml-st-string-statuses.php',
    'WPML_ST_Strings' => $baseDir . '/classes/class-wpml-st-strings.php',
    'WPML_ST_TM_Jobs' => $baseDir . '/classes/wpml-tm/class-wpml-st-tm-jobs.php',
    'WPML_ST_Upgrade' => $baseDir . '/classes/upgrade/class-wpml-st-upgrade.php',
    'WPML_ST_Upgrade_Migrate_Originals' => $baseDir . '/classes/upgrade/class-wpml-st-upgrade-migrate-originals.php',
    'WPML_ST_User_Fields' => $baseDir . '/classes/class-wpml-st-user-fields.php',
    'WPML_ST_Verify_Dependencies' => $baseDir . '/classes/class-wpml-st-verify-dependencies.php',
    'WPML_ST_WP_Loaded_Action' => $baseDir . '/classes/actions/class-wpml-st-wp-loaded-action.php',
    'WPML_String_Translation_Table' => $baseDir . '/classes/string-translation-ui/class-wpml-string-translation-table.php',
    'WPML_TM_Filters' => $baseDir . '/classes/filters/class-wpml-tm-filters.php',
    'WPML_TM_Widget_Filter' => $baseDir . '/classes/filters/class-wpml-tm-widget-filter.php',
    'WPML_Twig_WP_Plugin_Extension' => $vendorDir . '/wpml/commons/src/twig-extensions/wpml-twig-wp-plugin-extension.php',
    'WPML_post_slug_translation_settings' => $baseDir . '/classes/slug-translation/class-wpml-post-slug-translation-settings.php',
    'xrstf\\Composer52\\AutoloadGenerator' => $vendorDir . '/xrstf/composer-php52/lib/xrstf/Composer52/AutoloadGenerator.php',
    'xrstf\\Composer52\\Generator' => $vendorDir . '/xrstf/composer-php52/lib/xrstf/Composer52/Generator.php',
);
