<?php

// autoload_52.php generated by xrstf/composer-php52

require_once dirname(__FILE__) . '/composer'.'/autoload_real_52.php';

return ComposerAutoloaderInit19e8f9b45e781f264699383aef3dbce8::getLoader();
